services:
  api:
    env_file:
      - ../../control-panel/.env.production
  client:
    env_file:
      - ../../control-panel/.env.production
  spot_grid_bot:
    env_file:
      - ../../spot_grid_bot/.env.production
