include:
  - path: ./docker-compose.infra.yaml
  - path: ./docker-compose.apps.yaml
  - path: ./docker-compose.observability.yaml
  - path: ./docker-compose.mailpit.yaml
  - path: ./docker-compose.trading.yaml
