"""Pure Spot Grid domain package."""

from bot_platform_service.trading_bots.spot_grid.domain.de_risk import (
    DE_RISK_ALLOWED_REGIMES,
    build_de_risk_intents,
    de_risk_diagnostics,
)
from bot_platform_service.trading_bots.spot_grid.domain.exposure import compute_exposure
from bot_platform_service.trading_bots.spot_grid.domain.grid_planner import SpotGridPlanner
from bot_platform_service.trading_bots.spot_grid.domain.indicator_policy import (
    INDICATOR_LIBRARY_DECISION,
    INDICATOR_LIBRARY_DECISION_VERSION,
    REJECTED_INDICATOR_LIBRARY_CANDIDATES,
    SELECTED_INDICATOR_LIBRARY,
    SELECTED_INDICATOR_LIBRARY_DEPENDENCY,
    IndicatorLibraryDecision,
    normalize_indicator_decimal,
)
from bot_platform_service.trading_bots.spot_grid.domain.indicators import (
    ATR_LENGTH,
    EMA_FAST_LENGTH,
    EMA_MID_LENGTH,
    EMA_SLOW_LENGTH,
    IndicatorRuntime,
    REALIZED_VOLATILITY_LENGTH,
    REALIZED_VOLATILITY_SHORT_LENGTH,
    RSI_LENGTH,
    StockIndicatorsRuntime,
    VOLUME_MA_LENGTH,
    compute_core_indicators,
    load_stock_indicators_runtime,
)
from bot_platform_service.trading_bots.spot_grid.domain.market_structure import (
    DEFAULT_STRUCTURE_LOOKBACK,
    DEFAULT_STRUCTURE_SWING_WINDOW,
    MIN_STRUCTURE_CANDLES,
    SUPPORT_RESISTANCE_CANDIDATE_LIMIT,
    compute_market_structure,
)
from bot_platform_service.trading_bots.spot_grid.domain.models import (
    GridLevel,
    GridLevelSide,
    IndicatorCandle,
    IndicatorInput,
    IndicatorSnapshot,
    MarketRegime,
    MarketStructureBias,
    MarketStructureSnapshot,
    PortfolioAllocationSnapshot,
    PortfolioContext,
    PortfolioExposureSnapshot,
    PositionContext,
    PriceBand,
    RegimeSnapshot,
    RegimeStateSnapshot,
    SpotGridCandle,
    SpotGridConfig,
    SpotGridPlan,
    StrategyDecision,
    StrategyGuardSnapshot,
    StrategyRiskLimits,
    SupportResistanceCandidate,
    SymbolExposureSnapshot,
    SwingPoint,
    TargetExecutionIntent,
    TargetIntent,
    TargetIntentType,
    UnderwaterPositionSnapshot,
    UnderwaterStateSnapshot,
    normalize_spot_grid_symbol,
)
from bot_platform_service.trading_bots.spot_grid.domain.portfolio_allocator import allocate_portfolio_budget
from bot_platform_service.trading_bots.spot_grid.domain.recovery import (
    build_recovery_averaging_intents,
    recovery_averaging_diagnostics,
)
from bot_platform_service.trading_bots.spot_grid.domain.position_intent_contract import (
    POSITION_INTENT_ALERT_EXAMPLE,
    POSITION_INTENT_ENTRY_EXAMPLE,
    POSITION_INTENT_EXAMPLES,
    POSITION_INTENT_EXIT_EXAMPLE,
    POSITION_INTENT_HOLD_EXAMPLE,
    POSITION_INTENT_PAYLOAD_SCHEMA,
    POSITION_INTENT_PAYLOAD_SCHEMA_VERSION,
    POSITION_INTENT_REBALANCE_EXAMPLE,
)
from bot_platform_service.trading_bots.spot_grid.domain.regime_detector import (
    ATR_RATIO_HIGH_VOLATILITY_THRESHOLD,
    DOWNTREND_RSI_THRESHOLD,
    HIGH_VOLATILITY_THRESHOLD,
    UPTREND_RSI_THRESHOLD,
    detect_single_timeframe_regime,
)
from bot_platform_service.trading_bots.spot_grid.domain.regime_state_machine import (
    COOLDOWN_REGIMES,
    REGIME_TRANSITION_CONFIRMATIONS,
    regime_state_key,
    resolve_regime_state,
)
from bot_platform_service.trading_bots.spot_grid.domain.semantic_intent import (
    build_semantic_intent_hash,
    semantic_intent_payload,
)
from bot_platform_service.trading_bots.spot_grid.domain.target_intent_signal import target_intent_to_bot_signal
from bot_platform_service.trading_bots.spot_grid.domain.underwater import (
    RECOVERY_ALLOWED_REGIMES,
    detect_underwater_state,
)

__all__ = [
    "GridLevel",
    "GridLevelSide",
    "ATR_LENGTH",
    "ATR_RATIO_HIGH_VOLATILITY_THRESHOLD",
    "COOLDOWN_REGIMES",
    "DE_RISK_ALLOWED_REGIMES",
    "DEFAULT_STRUCTURE_LOOKBACK",
    "DEFAULT_STRUCTURE_SWING_WINDOW",
    "DOWNTREND_RSI_THRESHOLD",
    "EMA_FAST_LENGTH",
    "EMA_MID_LENGTH",
    "EMA_SLOW_LENGTH",
    "IndicatorRuntime",
    "HIGH_VOLATILITY_THRESHOLD",
    "REALIZED_VOLATILITY_LENGTH",
    "REALIZED_VOLATILITY_SHORT_LENGTH",
    "RECOVERY_ALLOWED_REGIMES",
    "REGIME_TRANSITION_CONFIRMATIONS",
    "IndicatorCandle",
    "IndicatorInput",
    "INDICATOR_LIBRARY_DECISION",
    "INDICATOR_LIBRARY_DECISION_VERSION",
    "IndicatorSnapshot",
    "IndicatorLibraryDecision",
    "MIN_STRUCTURE_CANDLES",
    "MarketRegime",
    "MarketStructureBias",
    "MarketStructureSnapshot",
    "POSITION_INTENT_ENTRY_EXAMPLE",
    "POSITION_INTENT_ALERT_EXAMPLE",
    "POSITION_INTENT_EXAMPLES",
    "POSITION_INTENT_EXIT_EXAMPLE",
    "POSITION_INTENT_HOLD_EXAMPLE",
    "POSITION_INTENT_PAYLOAD_SCHEMA",
    "POSITION_INTENT_PAYLOAD_SCHEMA_VERSION",
    "POSITION_INTENT_REBALANCE_EXAMPLE",
    "PortfolioAllocationSnapshot",
    "PortfolioContext",
    "PortfolioExposureSnapshot",
    "PositionContext",
    "PriceBand",
    "RegimeSnapshot",
    "RegimeStateSnapshot",
    "REJECTED_INDICATOR_LIBRARY_CANDIDATES",
    "SELECTED_INDICATOR_LIBRARY",
    "SELECTED_INDICATOR_LIBRARY_DEPENDENCY",
    "SpotGridCandle",
    "SpotGridConfig",
    "SpotGridPlan",
    "SpotGridPlanner",
    "StockIndicatorsRuntime",
    "StrategyDecision",
    "StrategyGuardSnapshot",
    "StrategyRiskLimits",
    "SUPPORT_RESISTANCE_CANDIDATE_LIMIT",
    "SupportResistanceCandidate",
    "SymbolExposureSnapshot",
    "SwingPoint",
    "TargetExecutionIntent",
    "TargetIntent",
    "TargetIntentType",
    "UnderwaterPositionSnapshot",
    "UnderwaterStateSnapshot",
    "RSI_LENGTH",
    "UPTREND_RSI_THRESHOLD",
    "VOLUME_MA_LENGTH",
    "allocate_portfolio_budget",
    "build_recovery_averaging_intents",
    "build_de_risk_intents",
    "build_semantic_intent_hash",
    "compute_core_indicators",
    "compute_exposure",
    "compute_market_structure",
    "detect_single_timeframe_regime",
    "detect_underwater_state",
    "de_risk_diagnostics",
    "load_stock_indicators_runtime",
    "normalize_indicator_decimal",
    "normalize_spot_grid_symbol",
    "recovery_averaging_diagnostics",
    "regime_state_key",
    "resolve_regime_state",
    "semantic_intent_payload",
    "target_intent_to_bot_signal",
]
