export enum SecurityEventType {
    LOGIN_SUCCESS = 'login_success',
    REGISTRATION_SUCCESS = 'registration_success',
    LOGIN_FAILED = 'login_failed',
    LOGOUT = 'logout',
    SESSION_REVOKED = 'session_revoked',
    REVOKE_OTHER_SESSIONS = 'revoke_other_sessions',
    REVOKE_ALL_SESSIONS = 'revoke_all_sessions',
    REFRESH_FAILED = 'refresh_failed',
    PASSWORD_CHANGED = 'password_changed',
    PASSWORD_RESET_COMPLETED = 'password_reset_completed',
    EMAIL_CHANGE_REQUESTED = 'email_change_requested',
    EMAIL_VERIFIED = 'email_verified',
    SUSPICIOUS_DEVICE = 'suspicious_device',
    LOGIN_APPROVAL_REQUIRED = 'login_approval_required',
    LOGIN_APPROVAL_PASSED = 'login_approval_passed',
    LOGIN_APPROVAL_FAILED = 'login_approval_failed',
    LOGIN_APPROVAL_EXPIRED = 'login_approval_expired',
    LOGIN_APPROVAL_RESENT = 'login_approval_resent',
    LOGIN_APPROVAL_RESEND_FAILED = 'login_approval_resend_failed',
    RE_AUTH_PASSED = 're_auth_passed',
    RE_AUTH_FAILED = 're_auth_failed',
}
